language: node_js
node_js:
   - "0.10"
env:
  global:
    - secure: "JH7N4LAjAywkt010l+20n3FWsrzX2bjzvm+wKf04+IIoNp6QTkYqRFTT6uII\n1Fqs2x0H5cyPgum/ji++vdFLOKkusKTTUdqDr3a8296wdIxm3VpXCusjHqkP\nnpL5SYGuUPyAfIT5YOstO7kfk11Nuex9bWb1mmF/JcBI7P+AbLI="
    - MAJOR_VERSION: 0
    - MINOR_VERSION: 1
    - REVISION: 0

before_script:
    - export VERSION="${MAJOR_VERSION}.${MINOR_VERSION}.${REVISION}.${TRAVIS_BUILD_NUMBER}"
    - npm install -g typescript
    - npm install jade
    - npm install fs-extra
    - npm install js-yaml
    - npm install optimist
    - npm -g install closurecompiler
    - mkdir "${HOME}/temp_tools"
    - "curl -o ${HOME}/temp_tools/JsTestDriver-1.3.3d.jar 'http://js-test-driver.googlecode.com/files/JsTestDriver-1.3.3d.jar'"
    - "java -jar ${HOME}/temp_tools/JsTestDriver-1.3.3d.jar --port 9876 &"
    - "sleep 3"
    - "phantomjs scripts/phantomjs-jstd.js &"
    - "sleep 3"

script:
    - mkdir out
    - node scripts/build_core.js --configuration debug
    - node scripts/build_core.js --configuration release --outFileName out/john-smith.js --outMinFileName out/john-smith.min.js
    - cp out/john-smith.debug.js out/john-smith-${VERSION}.debug.js &
    - cp out/john-smith.js out/john-smith-${VERSION}.js &
    - cp out/john-smith.min.js out/john-smith-${VERSION}.min.js
    - java -jar ${HOME}/temp_tools/JsTestDriver-1.3.3d.jar --config test/config.jstd --tests all --server http://localhost:9876 --testOutput out
    - "node scripts/build_tutorial.js"
    - "mkdir ${HOME}/build_artifacts"
    - "cp -R out/* ${HOME}/build_artifacts"
    - "git config --global user.email 'guryanovev@gmail.com'"
    - "git config --global user.name 'Travis'"
    - "git remote add upstream https://${GH_TOKEN}@github.com/guryanovev/JohnSmith.git"
    - "git checkout --orphan gh-pages"
    - "rm -r *"
    - "git rm -rf ."
    - "cp -R ${HOME}/build_artifacts/* ."
    - "git add -f ."
    - git commit -q -m "Travis build $TRAVIS_BUILD_NUMBER pushed to gh-pages"
    - "git push -fq upstream gh-pages"
