language: node_js
node_js:
   - "0.10"
env:
  global:
    - secure: "JH7N4LAjAywkt010l+20n3FWsrzX2bjzvm+wKf04+IIoNp6QTkYqRFTT6uII\n1Fqs2x0H5cyPgum/ji++vdFLOKkusKTTUdqDr3a8296wdIxm3VpXCusjHqkP\nnpL5SYGuUPyAfIT5YOstO7kfk11Nuex9bWb1mmF/JcBI7P+AbLI="
script:
    - "node scripts/build_tutorial.js"
    - "mkdir ${HOME}/build_artifacts"
    - "cp -R out ${HOME}/build_artifacts"
    - "rm *"
    - "cp -R ${HOME}/build_artifacts ."
    - "git config --global user.email 'guryanovev@gmail.com'"
    - "git config --global user.name 'Travis'"
    - "git remote add upstream https://${GH_TOKEN}@github.com/guryanovev/JohnSmith.git"
    - "git checkout -B gh-pages"
    - "git add -f ."
    - "git commit -q -m 'Travis build ${TRAVIS_BUILD_NUMBER} pushed to gh-pages'"
    - "git push -fq upstream gh-pages"
